/*
Inserting data into tables
*/

-- Inserting 77 districts of Nepal into 'districts' table
INSERT INTO districts (district_name) VALUES
('Jhapa'),
('Ilam'),
('Panchthar'),
('Taplejung'),
('Tehrathum'),
('Sankhuwashabha'),
('Bhojpur'),
('Dhankuta'),
('Morang'),
('Sunsari'),
('Udayapur'),
('Khotang'),
('Solukhumbu'),
('Okhaldhunga'),
('Saptari'),
('Siraha'),
('Dhanusha'),
('Mahottari'),
('Sarlahi'),
('Rautahat'),
('Bara'),
('Parsa'),
('Sindhuli'),
('Ramechhap'),
('Dolakha'),
('Kavrepalanchowk'),
('Sindhupalchowk'),
('Bhaktapur'),
('Kathmandu'),
('Lalitpur'),
('Makwanpur'),
('Chitwan'),
('Dhading'),
('Nuwakot'),
('Rasuwa'),
('Gorkha'),
('Manang'),
('Mustang'),
('Lamjung'),
('Kaski'),
('Myagdi'),
('Syangja'),
('Tanahu'),
('Baglung'),
('Parbat'),
('Nawalpur (Nawalparasi East)'),
('Nawalparasi (west)'),
('Rupendehi'),
('Palpa'),
('Kapilbastu'),
('Arghakhachi'),
('Gulmi'),
('Pyuthan'),
('Dang'),
('Rolpa'),
('Rukum (East)'),
('Banke'),
('Bardiya'),
('Salyan'),
('Rukum (West)'),
('Dolpa'),
('Jajarkot'),
('Surkhet'),
('Dailekh'),
('Kalikot'),
('Jumla'),
('Mugu'),
('Humla'),
('Kailali'),
('Kanchanpur'),
('Doti'),
('Achham'),
('Bajura'),
('Dadeldhura'),
('Bajhang'),
('Baitadi'),
('Darchula');


INSERT INTO addresses (address_line1, city, )

INSERT INTO companies (company) VALUES
('Aprilia'),
('Bajaj'),
('Benelli'),
('BMW'),
('Crossfire'),
('Hero'),
('Honda'),
('KTM'),
('Royal Enfield'),
('Yatri');

INSERT INTO colors (color, hex) VALUES
('Black', '000000'),
('GunMetal Grey', '8D918D')
('White', 'FFFFFF'),
('Orange', 'FF6600');

