GET http://localhost:3001/api/users HTTP/1.1

###
POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
    "email" : "hemsir4@yahoo.com",
    "fullName" : "Hemlal Dulal",
    "password" : "root-user",
    "phone": "98674",
    "userStatus":"Y"
}

###
POST http://localhost:3001/api/login HTTP/1.1
Content-Type: application/json

{
    "email" : "hemsir4@yahoo.com",
    "password" : "root-user"
}


###
PUT http://localhost:3001/api/users/2 HTTP/1.1
Content-Type: application/json

{
    "email" : "restfulapi@yahoo.com",
    "fullName" : "Janardan Sharma",
    "pwdHash" : "loremipsumtextgenerate",
    "phone" : "999999"
}

###
DELETE http://localhost:3001/api/users/2 HTTP/1.1

###
GET http://localhost:3001/api/address/ HTTP/1.1

###
POST http://localhost:3001/api/address/ HTTP/1.1
Content-Type: application/json

{
    "line1":"Na: tole",
    "city": "Lalitpur",
    "districtId": 1
}